"""update

Revision ID: a4820256de75
Revises: 2af94a15342d
Create Date: 2025-02-24 23:21:29.383376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4820256de75'
down_revision = '2af94a15342d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.alter_column('seats_available',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.alter_column('seats_available',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
